language: python
python:
    - 2.7
before_install:
    - date -u
    - uname -a
    - lsb_release -a
    - sudo apt-get -qq update
    - sudo apt-get -y install curl build-essential python-dev samtools '^zlib.*-dev$'
    - git clone https://github.com/lh3/wgsim.git 
    - cd wgsim && gcc -g -O2 -Wall -o wgsim wgsim.c -lz -lm && cd ..
    - sudo cp wgsim/wgsim /usr/bin/wgsim
    - curl -L https://github.com/lh3/bwa/archive/0.7.12.tar.gz | tar xz
    - cd bwa-0.7.12 && make && cd ..
    - sudo cp bwa-0.7.12/bwa /usr/bin
install:
    - pip install coveralls
    - python setup.py install
script:
    - nosetests --with-coverage --cover-package=bones
after_success:
    - coveralls
